services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    image: agile-ai-backend
    container_name: agile-ai-backend

    ports:
      - "4000:4000"

    environment:
      - NODE_ENV=production
      - PORT=4000
      - OLLAMA_URL=http://host.docker.internal:11434
      # host.docker.internal allows the container to access services running on the host machine, such as the Ollama server.

    volumes:
      - ./projects:/app/projects
      - ./logs:/app/logs

    restart: unless-stopped

    tty: true
    stdin_open: true